### ISSUE TITLE
Deployments with a docker on MacOs

### ISSUE THREAD

**Issue by AnastasiiaL** [input-output-hk/mantis-ops#42]
running `nix build .#nomadJobs.mantis-staging-mantis.run` in a nix-shell in docker results in 

mantis> /nix/store/d4nnpcb28m9l1556ag8pxczapp2mmjbf-stdenv-linux/setup: line 1308:   302 Killed                  sbt stage -Dnix=true
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------ nix
builder for '/nix/store/kszgacdv6gfdsk0hm4xg3bmx86b7zv34-mantis-3.2.1.drv' failed with exit code 137
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------ nix
1 dependencies of derivation '/nix/store/3dw8fzklhhl7bnsamw9mnhanfgmbcryb-docker.mantis.ws-mantis-bulk-layers.drv' failed to build
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------ nix
1 dependencies of derivation '/nix/store/7nwwyr0ykvwpqkaxsyggx2fnygrilldr-mantis.mini.json.drv' failed to build
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------ nix
1 dependencies of derivation '/nix/store/cnlavwbcfhlhlszw7k78ddijlq3igv27-docker.mantis.ws-mantis-conf.json.drv' failed to build
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------ nix
1 dependencies of derivation '/nix/store/yfb9b8qbmp1dv1maz2h8h9gcdrg203nf-nomad-run.drv' failed to build

**Comment by jvdp** [comment]
I think Docker needs more memory for this. For reference:

![image](https://user-images.githubusercontent.com/241947/109524834-3d3add00-7ab1-11eb-82c0-5ae3afb76249.png)

**Comment by AnastasiiaL** [comment]
right, just increased the memory from 2 to 4 GB and it succeeded then. Closing the issue.
